applications:
- name: revampd-api
  memory: 64M
  path: ../../src
  command: ./bin/revampd
  stack: cflinuxfs3
  buildpacks:
  - go_buildpack
  services:
  # defined in bin/setup-cloudgov
  - revampd-psql
  env:
    GOVERSION: go1.12
    GOPACKAGENAME: github.com/USEPA/revampd
