name: Build and test

on:
  
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    env:
      CF_USERNAME: ${{ secrets.deployerusername }}
      CF_PASSWORD: ${{ secrets.deployerpw }}
        
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make

    - name: Build for scan
      if: ${{ success() }}
      run: docker-compose up -d

    - name: ZAP Scan
      if: ${{ success() }}
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'http://localhost:9080'
        cmd_options: '-I' # Don't fail on WARNings

    - name: clean up after scan
      run: docker-compose down
      
    