name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PORT: 2019
      DATABASE_URL: postgres://postgres@db:5432/postgres?sslmode=disable
 
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make
