name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    env:
      SOURCE_DIR: '' #insert source director
      CF_USERNAME: ${{ secrets.deployerusername }}
      CF_PASSWORD: ${{ secrets.deployerpw }}
        
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make

  deploy:
    #machine:
    #working-directory:
    #environment:
    steps:
      - login:
        name: CF Login
        command: |
          cf_run() {
            docker run \
            --rm \
            -v $HOME/.cf:/root/.cf \
            -v $PWD:/app \
            -w /app \
            governmentpaas/cf-cli \
            cf "$@"
        }
      - run:
        name: Deploy revampd
        command: |
        #insert cf push commands 
