name: Build, test, deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build, test, deploy
    runs-on: ubuntu-latest
    
    env:
      CF_USERNAME: ${{ secrets.deployerusername }}
      CF_PASSWORD: ${{ secrets.deployerpw }}
        
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make

    - name: Build for scan
      if: ${{ success() }}
      run: docker-compose up -d

    - name: ZAP Scan
      if: ${{ success() }}
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'http://localhost:9080'
        cmd_options: '-I' # Don't fail on WARNings

    - name: clean up after scan
      run: docker-compose down
      


    - name: Make the cloudgov-deploy script executable
      if: ${{ success() }}
      run: chmod +x ./bin/deploy-cloudgov
    
    - name: Deploy the app to cloud.gov
      if: ${{ success() }}
      run: ./bin/deploy-cloudgov
      
    