name: Build, test, deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build, test, deploy
    runs-on: ubuntu-latest
    
    env:
      CF_USERNAME: ${{ secrets.deployerusername }}
      CF_PASSWORD: ${{ secrets.deployerpw }}
        
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make
      
    - name: Ping docker container
      # frontend
      run: |
        ip addr show docker0
        ping -W 5 172.17.0.1
        nmap -p 9080 172.17.0.1
      
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'http://172.17.0.1:9080'
    
    - name: Make the cloudgov-deploy script executable
      if: ${{ success() }}
      run: chmod +x ./bin/deploy-cloudgov
    
    - name: Deploy the app to cloud.gov
      if: ${{ success() }}
      run: ./bin/deploy-cloudgov
