name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    env:
      SOURCE_DIR: '' #insert source director
      SPACE_DEPLOYER_USERNAME: ${{ secrets.deployerusername }}
      SPACE_DEPLOYER_PW: ${{ secrets.deployerpw }}
        
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and test
      run: docker-compose run --rm api make
      
        
