name: Sync to Bitbucket

on:
  schedule: 
    # Run weekly at 11:59PM on Friday
    # - cron: '59 23 * * 5'
    - cron: "50 20 * * 3"

jobs:
  push: 
    name: Push master to Bitbucket
    runs-on: "ubuntu-latest"
    
#    env:
#      BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
#      BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}

    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master

    - name: Push to Bitbucket
      run: |
          git log | head 
##        git push --set-upstream https://"$BITBUCKET_USERNAME":"$BITBUCKET_TOKEN"@bitbucket.epa.gov/scm/revampd/revampd.git master

